### ISSUE TITLE
OpenSeaDragon as the zoomable viewer embedded in the website

### ISSUE THREAD

**Issue by klokan** [klokantech/bmarchives-tickets#10]
Let's use http://openseadragon.github.io/ as the zoomable viewer.

The photos should be displayed via image links (part of URL is specification of the width/height - so thumbnail / middle / full size may be done programmatically in JavaScript). It is different from standard Omeka on this project.

The high resolution maps to be displayed via DeepZoom protocol from the image server:
http://www.bmarchives.org/cgi-bin/iipsrv.fcgi?deepzoom=BM_Maps_100200490.jp2.dzi
http://www.bmarchives.org/cgi-bin/iipsrv.fcgi?deepzoom=BM_Maps_100200490.jp2_files/8/0_0.jpg

**Comment by klokan** [comment]
29-11-2013: Yes. Both maps and images as they exists in the website (smaller resolution version).

**Comment by klokan** [comment]
@xurban42 starts to work on this now

**Comment by xurban42** [comment]
Done.
OpenSeaDragon has IE8 bug with control buttons: https://github.com/openseadragon/openseadragon/issues/272
