### ISSUE TITLE
Nature's self printing - import new images into the web

### ISSUE THREAD

**Issue by klokan** [klokantech/bmarchives-tickets#13]
We need to import new images provided on the harddisk into the online storage to have a 1200px size and thumbnails online.

Then import relevant records to the BMArchives database - so that the images appears assigned to the right records of a (type Text).

The records are pages in a book, but each page has an individual record from Docustore already visible on the web.

An example:
http://www.bmarchives.org/items/show/100210607

**Comment by klokan** [comment]
We are waiting for an Excel sheet which binds the filenames of images provided on HDD to correct Docustore identifiers.

**Comment by klokan** [comment]
Still waiting for the Excel sheet.

**Comment by AnkeSR** [comment]
Sorry about the delay in answering. I did a spot check of the excel table, the docustore entries and the corresponding digitals and they are fine this side. I will send the excel table via email.

**Comment by klokan** [comment]
Files are renamed appropriately, rescaled to 1200px max size, uploaded to intranet in a zip:
https://docs.google.com/a/klokantech.com/file/d/0BwUe1kqIRJWScjVnYWZlS3lJaEE/edit?usp=sharing

The renamed unified full-size JPEG files are also stored on the hardisk.
The complete list is: https://gist.github.com/klokan/5457995

Next step is binding the reference to the identifier (e.g. "C.325.I.U1" to "100210166") and starting the import into database and into the image hosting. Then it will appear in the website.

Careful, some records contain _suffix:
http://www.bmarchives.org/browse/#q=C.325.I.U1&v=3

Note:

```
for i in *Hunziker_*; do cp $i renamed/`echo $i | sed 's/.*Hunziker/C.325/' | sed 's/_/\./g'`; done;
# rename manually the exception such as:
# C.325.II.U4.Prägung.jpg to C.325.II.U4_Prägung.jpg - careful with ä in filename
# C.325.II.0133 should be C.325.II.133
# .. etc
for i in *jpg; do convert $i -resize 1200x1200 ../final/$i; done;
```

**Comment by o1da** [comment]
Please check it.

**Comment by klokan** [comment]
Missing image in the http://www.bmarchives.org/items/show/100210167, as mentioned in the comment above:
Careful, some records contain suffix: http://www.bmarchives.org/browse/#q=C.325.I.U1&v=3 :-(

**Comment by o1da** [comment]
Suffix wasn't problem generally - another records with suffix were ok. But suffix itself in record 100210167 was wrong - reference "C.325.I.U1_medaillon" in database vs "C.325.I.U1_Medaillion" from nature-urls.csv
I tried many things and was confused, but problem was in data instead...
