### ISSUE TITLE
Georeferencer - new import of the maps which are geographically in groups

### ISSUE THREAD

**Issue by klokan** [klokantech/bmarchives-tickets#15]
e.g. maps should be in "collections" in the Excel sheet - so that people can choose a random map for selected geographical area.

**Comment by klokan** [comment]
KlokanTech will import all maps, we have to create metadata XLS in the format: http://help.georeferencer.com/metadata

**Comment by klokan** [comment]
Import finalised in Dec 2014.
2908 maps at http://www.bmarchives.org/georeferencer/

**Comment by klokan** [comment]
All the maps are now imported as a single group. To be revisited.

**Comment by klokan** [comment]
Verify existence of the links from detail page.

**Comment by klokan** [comment]
The groups were specified only vaguely by Anke in email with subject "List of maps" from 2012-11-13.
Attachment: https://drive.google.com/file/d/0BwUe1kqIRJWSZUFHZGR0eDFyaTh3TDRZM2VjS1Y5N1ZuckY0/view?usp=sharing

The complete list of 5013 maps was exported by Olda from the database in the email with subject "export map bmarchives":
https://drive.google.com/file/d/0BwUe1kqIRJWSekhVWDBjaTZpbTRLTy1yMURIUzRiYXRRNkUw/view?usp=sharing

**Comment by daliborjanak** [comment]
Imported: https://docs.google.com/spreadsheets/d/1qnHABg7-rQXcWOu__oHSJ0JdW1hpX2aSb50vZb3375Y/edit?usp=sharing
Timestamps were edited to format for georeferencer.
