### ISSUE TITLE
PayPal account & payment issue

### ISSUE THREAD

**Issue by AnkeSR** [klokantech/bmarchives-tickets#20]
Paypal payments are not being deposited on the mission 21 account but on info@bmarchives.org, to which we have no access. There seems to be a problem with the link of the icon and the connected account. Can you send me any information which may assist before I contact paypal directly? Thanks

**Comment by o1da** [comment]
I change the link of the icon to mission 21 account. But it itself doesn't solve past payments, please try to add email address info@bmarchives.org to your mission 21 account as alias email. It can be done from 
PayPal -> My Account -> Profile -> Add or Edit Email -> Add
It should pair past payments to your correct account, if not - contact paypal directly would be necessary.

**Comment by klokan** [comment]
@AnkeSR What is the status of this issue? Is it now resolved?

**Comment by AnkeSR** [comment]
Yes, we managed to resolve it last week. Thanks!

**Comment by klokan** [comment]
Great. I am closing the ticket.
