### ISSUE TITLE
Search issue

### ISSUE THREAD

**Issue by AnkeSR** [klokantech/bmarchives-tickets#22]
I have been doing a lot of corrections in the meta data of maps and am struggling to find the maps under their titles, e.g.

Carte des Missions (here the English translation is "Map of missions"). If I enter the reference no. it is no problem but otherwise it doesn't seem to search in the title of the map.

**Comment by klokan** [comment]
Could you please provide this info:
- the link to this problematic map on the bmarchives.org website (with reference no. in url?) so we can see the updated record. I expect the update from Docustore is visible on the web just fine.
- description of what do you exactly type in the search box in /browse or even better:
- a link (copy&paste of the address bar in you web browser ) so we can reproduce this same query as you are trying
- what version of web browser do you use

Thanks. Petr

**Comment by AnkeSR** [comment]
I will try my best:
1. Map: General Map of the Gold Coast

First I entered 'General Map of the Gold Coast' in the search box on the homepage and clicked on the fulltext search option that appears in the dropdown. Unfortunately, in this case, it automatically goes to the "search all records" page instead of showing results. If I enter the old reference number (97278) on the homepage, nothing happens. If I enter the reference number (and not the title) in the search box on the "search all records" page, I get the map (http://www.bmarchives.org/browse/#q=97278 / http://www.bmarchives.org/items/show/100202452).
1. This goes for all the following maps:

97279 (Title: Gold Coast Survey. General Map of the Gold Coast and that Part of Togoland mandated to Great Britain
97282 (Title: Gold Coast Survey. General Map of the Gold Coast and that Part of Togoland mandated to Great Britain
97303(Title: Gold Coast Survey. General Map of the Gold Coast and that Part of Togoland mandated to Great Britain
KARVAR-31.110  General Map of the Gold Coast  (I couldn't find this map at all; neither with the reference number nor with the tite or per curtain - it does feature in Docustore, though)
97908 (Title: Carte des Missions)

**Comment by klokan** [comment]
We have fixed this issue - the search should provide the results with an improved ranking and higher relevance.
Now we do performance testing to possibly improve the speed of the fulltext search as well.

**Comment by klokan** [comment]
Fixed.

The search now prioritise title - so results are more relevant. @AnkeSR, could you please confirm you are satisfied with the results?
Reimplementation of the search has been done to ensure very fast data retrieval.

**Comment by AnkeSR** [comment]
Generally, the search is faster and efficient, if you prioritise title and not popularity after initial search entry. The search for "carte des missions" still however does not feature in at least the first 5-10 search results which indicates that we would need both title and alternate title to be searched. Is this possible?

**Comment by klokan** [comment]
It is technically possible, but it may mean about 5 hours of work to do that, because we have to include the alternative title in the visible results list of the search to be able to index it. It also means reindexing the whole metadata database.

@AnkeSR Shall we do the work?

**Comment by AnkeSR** [comment]
I will get back to you on the subject by Thursday.

**Comment by klokan** [comment]
29-11-2013: To be done ASAP

**Comment by o1da** [comment]
It is done. Searching is now performed on combined fulltext index title and alt_title.
