### ISSUE TITLE
BM Archives responding very slowly

### ISSUE THREAD

**Issue by AnkeSR** [klokantech/bmarchives-tickets#23]
We have been struggling to open BM Archives since yesterday, it takes up to at least 30 seconds before it loads and searching is extremely delayed. Doesn't seem to be a problem on this side as other websites load well.

**Comment by o1da** [comment]
We have just solved this problem. Our server was under the "DDOS attack" from yesterday. It was overloaded with huge quantum of malicious requests. We filtered these requests away.

**Comment by AnkeSR** [comment]
Ah, that would explain the very strong delays. Thanks for letting me know.

**Comment by AnkeSR** [comment]
Just wanted to let you know that the website isn't responding.

**Comment by klokan** [comment]
This has been resolved the same day. Closing the ticket.
