### ISSUE TITLE
Return function of browser 

### ISSUE THREAD

**Issue by AnkeSR** [klokantech/bmarchives-tickets#25]
Return function of browser 

After having performed a search and opened one item, it is not possible to return to the search results by pressing back space or return button. This happens with Internet Explorer 9 but works fine with some firefox versions. 

This issue has been approach before:

https://github.com/klokantech/bmarchives-tickets/issues/6

Its important to be fixed, since our users from all over the world come with all different kinds of browsers.

**Comment by klokan** [comment]
Duplicate to #6. IE 9 has been added to the bug report.
