### ISSUE TITLE
Carousel sorting - order of thumbnails

### ISSUE THREAD

**Issue by AnkeSR** [klokantech/bmarchives-tickets#26]
Once you’ve selected (opened) an item within the search results back scrolling within the tile bar is inactive. Furthermore, it must be possible to return back to the search results sequence. It seems like after viewing one document, the sorting of the bar changes sometimes (might this be because of the sorting according to popularity?)

**Comment by AnkeSR** [comment]
Sorry it should be "Tile bar" (for lack of the proper name).

**Comment by klokan** [comment]
We call it "Carousel" (title of the ticket renamed).

This is going to be fixed together with #6. Carousel has been reimplemented completely for the compatibility with IE.

**Comment by klokan** [comment]
The back button in browser should now run. The order of items is influenced by popularity which can change by visiting the item - as described in #31. Closing.

**Comment by AnkeSR** [comment]
As quote by you:

We call it "Carousel" (title of the ticket renamed).

This is going to be fixed together with #6. Carousel has been reimplemented completely for the compatibility with IE

--> Only partially fixed: within in the first set of results of the carousal it works fine. As soon as you switch to the next set of results within the carousal with the arrow button and open an item,  the carousal changes the carousal order and you cannot switch back to the first set of results. 

Please try this:

Search for "slave m" --> open one item --> click on carousal arrow --> open an item in next set of items --> then you should see an inactive carousal arrow (back) and changed carousal order.  Tried uploading a screenshot, doesn't seem to work with our old browser.

One more issue: the deleted switch to next item arrows below the carousal in item view since reimplementation of carousal. I would suggest discussing this issue at our meeting on 29th November, as we need to discuss it among ourselves.

**Comment by klokan** [comment]
Discussed. To be fixed by #31.
