### ISSUE TITLE
Jumping from one single entry within the search results to the next: 

### ISSUE THREAD

**Issue by AnkeSR** [klokantech/bmarchives-tickets#27]
Jumping from one search result to the next is not possible; it jumps to the next (higher) reference no instead of the next object in the tile bar (carousel).

I.e.: Clicking on the right arrow on this page (blue) Should lead to the object in the red rectangle. But it does not. 

![screenshot5](https://f.cloud.github.com/assets/59284/1491679/f3205de0-47b3-11e3-970d-e538c85c71a6.jpg)
Screenshot 5

Instead it leads to this document, which is not even in the tile-bar.

![screenshot6](https://f.cloud.github.com/assets/59284/1491678/eafb10ba-47b3-11e3-8a02-be3839c5ea13.jpg)
Screenshot 6

**Comment by klokan** [comment]
Because of the bug #31 the buttons should be hidden by JavaScript in case the carousel is displayed. They stay in HTML. If carousel is not displayed (there are no active cookies) the buttons are visible and runs as before.

**Comment by o1da** [comment]
I have tested Matto solution and deploy it.
