### ISSUE TITLE
"I" missing

### ISSUE THREAD

**Issue by AnkeSR** [klokantech/bmarchives-tickets#28]
A further issue is the fact that some “i” are missing:

We checkt with the bmpix website. The “I”-information was available there for the examples, but is not on bmarchives. How did this happen/how can it be fixed?

![screenshot7](https://f.cloud.github.com/assets/59284/1491651/4d075a8a-47b3-11e3-8e2d-c38334860290.jpg)
Screenshot 7

http://www.bmarchives.org/items/show/61617

![screenshot8](https://f.cloud.github.com/assets/59284/1491655/5300609e-47b3-11e3-8a90-313aae84ffff.jpg)
Screenshot 8

**Comment by klokan** [comment]
Can you please provide link to BMPix as well?

This needs to be reviewed together with Andy @andreasnef 

It seems three is also a different record in categories for this name, without "(Mr)" suffix, which shows the "i", but only with name: http://www.bmarchives.org/items/show/35122

**Comment by AnkeSR** [comment]
Here one of the links to which the name is connected on bmpix:

http://bmpix.usc.edu/bmpix/controller/view/impa-m30093.html?x=1384873002707

Here the contents of the "i" box on bmpix:

Zürcher, Wilhelm (Mr)

Birth Date: 18.02.1900

Death Date: 25.12.1960

Place of birth: [leer]

Place of origin: Hörstetten {place of origin}

Wedding date: 06.08.32

Profession: farmer (Landwirt)

Relationships: Parents of Zürcher, Doris Monika (child);
 Married to Zürcher-Roggli, Emmy (Mrs);
 Parents of Zürcher, Wilhelm\* (child)

Basel Mission membership number: 2277

Date entered Basel Mission: 1924

Date sent out by Basel Mission: 1932

Mission area service: Cameroon {mission area} until 1937, Cameroon {mission area} until 1945, Cameroon {mission area} until 1952

Notes: In Cameroon: 1938 - 1945 and 1949 - 1952. In the 'List of Brethren' full first names are Jonathan Wilhelm.+

**Comment by andreasnef** [comment]
The respective information is published on http://m21.docuteam.ch/oaipmh/oai2.php?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:m21.docuteam.ch:61617

One detail, though: the marriage date is not displayed correctly as the year was given with two digits in the database – I just fixed that issue and assume we'll see tomorrow if that solved the issue.

**Comment by AnkeSR** [comment]
Can this issue be resolved by you with the information given by Andi Nef?

**Comment by klokan** [comment]
This is now fixed. The problem was with the characters "{" and "}" inside of the JSON string.
We are restoring the styling of the info boxes, then this ticket will be closed.

**Comment by klokan** [comment]
A second related problem detected with Minibio were NEWLINE characters in the OAI JSON string - which is not valid JSON (issue on export from DocuStore). To prevent this we are filtering out the new lines during printing to the web site.

**Comment by andreasnef** [comment]
Ok, no problem to remove them for OAI. However, in what other way do you want linebreaks to be encoded – I imagine we can't just ignore them? Do you have an example at hand?
