### ISSUE TITLE
Jump to page (bottom of page) 

### ISSUE THREAD

**Issue by AnkeSR** [klokantech/bmarchives-tickets#29]
We tried using the jump to function on Internet Explorer, Safari, Google Chrome and Android standard browser and it did not work.

Ther is a field for entering a page to jump to. But there is no button to jump to the page and pressing return does not do it either. All you can do is click the “next”/”last” arrows, which leads you to the next/last page. How can it be, that this was never tested/noticed?

**Comment by o1da** [comment]
I have tested Matto solution and deploy it.
