### ISSUE TITLE
PayPal Button

### ISSUE THREAD

**Issue by klokan** [klokantech/bmarchives-tickets#3]
Would it be possible to remove the payment button from below each image to the “contact” page (below the address) ? I have my first query regarding payment online and it is a payment for several images.

Please insert the button with the following header & text:

**Ordering**

Please contact us prior to purchase.

[button]

It would be great if this could happen by the beginning of next week, as for me to forward the payment to my customer.

Anke

**Comment by klokan** [comment]
Assigned to @o1da. Scheduled to be done latest on Friday Feb 8th and deployed on both servers.

**Comment by o1da** [comment]
It's done, please check it.
