### ISSUE TITLE
Popularity sorting by clicking on next influences order in pages

### ISSUE THREAD

**Issue by klokan** [klokantech/bmarchives-tickets#31]
Bug related to fix of the #27 and #26.

Solution needs to be discussed.

**Comment by klokan** [comment]
If we are coming from popularity sorted list the visit of a detail page is not adjusting popularity.

Implementation to be discussed internally @o1da. Probably cookie related.

**Comment by o1da** [comment]
It is ok, I'm testing $_COOKIE['settings'])->{'v'}->{'order'}->{'column'} != "popularity"
