### ISSUE TITLE
Automatic Content-Update not working

### ISSUE THREAD

**Issue by AnkeSR** [klokantech/bmarchives-tickets#34]
It seems the automatic (daily) content-update between Docustore and Bmarchives does not work anymore. I created several new entries in Docustore over the last two weeks which are still not findable in Bmarchives, i.e.: E-10.101 or B-10.40. Please check your logs and fix this. Thank you!

**Comment by klokan** [comment]
We are reviewing what the problem could be. First guess is that there is a not allowed special character in XML. Results to be reported soon.

**Comment by o1da** [comment]
There is a problem with oai server. I receive nothing from oai request. Try this request

http://46.4.125.220/oaipmh/oai2.php?verb=ListRecords&metadataPrefix=oai_dc&from=2014-01-01T00:00:00Z

It should returns all records from the start of this year, but it is empty.

So, we need to contact admin of oai server.

**Comment by andreasnef** [comment]
Ok, I'll check.

**Comment by andreasnef** [comment]
Identified, the ssl certificates have expired, so the updates were blocked. Am fixing it now.

**Comment by andreasnef** [comment]
Resolved. It might be good to run a global update at some point again.

**Comment by o1da** [comment]
Database is completely updated now.
