### ISSUE TITLE
Dates 

### ISSUE THREAD

**Issue by AnkeSR** [klokantech/bmarchives-tickets#37]
I see there is a problem with dates not reflected in the citation:

http://www.bmarchives.org/items/show/37634
http://www.bmarchives.org/items/show/34281
http://www.bmarchives.org/items/show/41608
http://www.bmarchives.org/items/show/100205676

It seems to be a problem within the non-photographic entries, as you can see here:

http://www.bmarchives.org/items/show/56645
http://www.bmarchives.org/items/show/57451

**Comment by klokan** [comment]
There are various ways how datums are transferred from the DocuStore into website in DublinCore format (early,late,proper). Fix based on this report is being made now.

**Comment by o1da** [comment]
It is done.
