### ISSUE TITLE
Email Spam

### ISSUE THREAD

**Issue by AnkeSR** [klokantech/bmarchives-tickets#38]
We are experiencing particularly high amounts of spam via our email account which says the following and cannto be filtered because they are coming from the contact form:

Contact from the web form - hahujju - IZcptirxDU​WX
----- Original message -----

X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
         d=1e100.net; s=20130820;
         h=x-gm-message-state:date:to:from:cc:reply-to:subject:message-id
          :mime-version:content-transfer-encoding:content-type;
         bh=xM1LmsrNRLQC+sclrWDhrv+4WhtjAz/JEQQl6K8ui/Y=;
         b=AkAaDZjeh13G9cB/ftg9hMQBYx7F4k9aq2sFfkNThekNGFJnJ7NuTJ9nqGwzD+AWs5
          9/GK/AOHeds33168CPKEehG8S0xik3FSZIpK1HENC6hgOtbuf+cHsRECDEKF5q2hlesu
          3+4+yOf4MwqV4t/1HExAha73aIPzrilmQ6QPEMdmLIWw9zI00W4bxJkmSTc4pnQ5dChe
          d4H4HhcyP25ud3+pKYeHrK/lr13aRZyhXE4tU2D7wZJt75N64TL+vLRePumkw55G1Rdu
          eHV0E2Z26cYkyTM0pzxD5KrS73TgEAEB2Hu1X8fFz1UGaNzuc+9euO+eU8Qxa2M44JZu
          TvoA==
 X-Gm-Message-State: ALoCoQlHr09pgBreqjYDwN39P5+GqnQ3jG3U4njmOeUe3ujFJFDsOO9jbi+NMjPMK0Tqg+MpEIKT
 X-Received: by 10.14.246.68 with SMTP id p44mr23729083eer.72.1393618438533;
         Fri, 28 Feb 2014 12:13:58 -0800 (PST)
 Return-Path: info@bmarchives.org
 Received: from www.bmarchives.org (vs838.server4u.cz. [2001:1568:f::838])
         by mx.google.com with ESMTPSA id m9sm14537092eeh.3.2014.02.28.12.13.57
         for <multiple recipients>
         (version=TLSv1 cipher=RC4-SHA bits=128/128);
         Fri, 28 Feb 2014 12:13:57 -0800 (PST)
 Date: Fri, 28 Feb 2014 21:13:56 +0100
 Return-Path: info@bmarchives.org
 To: wjfwakqai trwbjx@rjipfp.com
 From: info@bmarchives.org
 Cc: info@bmarchives.org
 Reply-To: info@bmarchives.org
 Subject: Contact from the web form - wjfwakqai - cAAqNxGXCCdmaElU
 Message-ID: d3eb6cf8db45f8e0a7fde87cdd381cd4@www.bmarchives.org
 X-Priority: 3
 X-Mailer: PHPMailer 5.2.1 (http://code.google.com/a/apache-extras.org/p/phpmailer/)
 MIME-Version: 1.0
 Content-Transfer-Encoding: 8bit
 Content-Type: text/plain; charset="utf-8"

**Comment by klokan** [comment]
A proper solution is to use reCaptcha - as it is visible for example at: http://www.bacarchive.org.uk/contact
This can be done after upgrade to new Omeka.

It seems that ignoring all messages containing "[link=" would solve this issue for now as well.

**Comment by o1da** [comment]
It is done
