### ISSUE TITLE
category title does not get changed

### ISSUE THREAD

**Issue by andreasnef** [klokantech/bmarchives-tickets#40]
Hi Petr
A couple of weeks ago, I chagned data entries affecting the category http://www.bmarchives.org/browse/#c=21098. According to the OAI-Interface the data in dc:subject has been updated for the curtain. However, this does not get reflected on the website. Would you mind taking a look at this issue?

Regards, Andreas

**Comment by o1da** [comment]
There is a problem on oai server side - we should contact their server admin.
Our oai client receives "500 - internal server error" response for correct queries. Can be checked in web browser too: 
http://46.4.125.220/oaipmh/oai2.php?verb=ListRecords&metadataPrefix=oai_dc&from=2014-01-01T00:00:00Z

**Comment by andreasnef** [comment]
Ok, I'll check.
Am 13.09.2014 11:12 schrieb "Oldrich Vykydal" notifications@github.com:

**Comment by andreasnef** [comment]
I cannot reproduce the 500 error, although I see that it did appear for some requests only (and that 2014-01-01 did work). What is the setup of the sync on your side? Is it still doing a daily update during night?

One other thing: Would you mind chaining the IP address to the respective hostname: m21.docuteam.ch? It might be that we change the server to a different infrastructure (with more resources) at some point.

Am 13.09.2014 um 14:28 schrieb Andreas Nef a.nef@docuteam.ch:

**Comment by o1da** [comment]
Oai server works now, I can't reproduce any error now too. But it obviously didn't work at saturday and some amount of time back too - there were some gaps between synchronizing. So I ran synchronizing from start of this year and it was succesfull.
All records are updated - please check it and eventually close this ticket.

Url of oai server is changed to m21.docuteam.ch

Oai client is setup to run sync at 23:59 every day, I add some protection against faulty oai server too.

**Comment by andreasnef** [comment]
Thanks, Oldrich!
