### ISSUE TITLE
Search function/browse curtain do not work anymore

### ISSUE THREAD

**Issue by andreasnef** [klokantech/bmarchives-tickets#41]
Just received the message from mission21 regarding these issues. I can reproduce these errors, but have to leave it to you to fix it.

**Comment by klokan** [comment]
Related to recent server upgrade. @o1da should be able to fix it soon.
I am sorry this slipped in.

**Comment by klokan** [comment]
@o1da 
The problem:

```
Uncaught Error: Invalid JSON string: <br />
<b>Deprecated</b>:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in <b>/var/www/www.bmarchives.org/plugins/Categories/service.php</b> on line <b>19</b><br />
[{"id":"1","name":"[Archives catalogue]","parent_id":null,"depth":"0","full_path":"[Archives catalogue]","leaf":"0","itemsCount":"67717...
```

It looks like upgrade to MySQLi functions and redeploy of the Omeka Categories plugin is the simplest and fastest solution: http://stackoverflow.com/questions/21797118/deprecated-mysql-connect

**Comment by o1da** [comment]
It is fixed, all mysql functions are changed to its mysqli equivalents.
