### ISSUE TITLE
Back button after search results does not run in IE8 and IE9

### ISSUE THREAD

**Issue by klokan** [klokantech/bmarchives-tickets#6]
If I search in bmarchives.org (any combination of parameters) and visit one of the records then by going "Back" with the browser button I am not getting the originally selected search query.

It runs well in Chrome, but not in IE8 and IE9.

**Comment by klokan** [comment]
@o1da: Please check this in IE. Report here what could be the reason. In case it is caused by an easily fixable bug in the old style JavaScript on the detail page, then let's fix it immediately.
If compiled JavaScript needs to be altered then we join this work with the other JavaScript issues with curtain / category selection and schedule the development.

**Comment by klokan** [comment]
This is the most urgent on the project now.

**Comment by o1da** [comment]
I'm unable to solve this problem now :( I see error in IE8 console in javascript from themes/BMArchives/items/show.php. It is on line 58 and it says that OMEKA.SEARCH is not defined while cookieSettings should be loaded. Console in firefox and chrome are clear. This problem doesn't arise always, only once from 3-5 attempts. I tried to comment out parts of source which are related with cookies, but without succes. I already tried to initialise OMEKA.SEARCH when it wasn't initialized, but it produced errors in compiled javascript.
I can keep searching, but it costs much time.

**Comment by klokan** [comment]
OK. Thank you. I will check it personally and we will probably schedule rewrite of this old code into Closure Tools, to be more stable and aligned with the rest of the website.

**Comment by klokan** [comment]
The rewrite of the code has happen - we are now internally testing the fix of this ticket - once it testing is over we deploy it on the production website.

**Comment by klokan** [comment]
We have a new implementation of the carousel for item page in the code repository. This can be soon deployed on the production server.

@o1da lets discuss schedule for finalisation of the testing and deployment.

**Comment by o1da** [comment]
I have tested Matto solution and deployed it.
