### ISSUE TITLE
Change header - remove Home, rename Categories, etc.

### ISSUE THREAD

**Issue by klokan** [klokantech/bmarchives-tickets#8]
The main menu should be adjusted according the screenshot (without too the extra margin on the left)

New items: Show all records | Browse | Advanced search

![Screen Shot 2013-04-09 at 3 40 29 PM](https://f.cloud.github.com/assets/59284/356945/13b8ebd4-a11b-11e2-90dd-d831f65f6ea2.png)

**Comment by o1da** [comment]
Please check it.

**Comment by klokan** [comment]
There should be a padding/margin between the items - as on the screenshot. But the "Show all records" should be aligned to the B letter of the logo. Please fix it ASAP.

**Comment by o1da** [comment]
Ok, menu items are aligned.

**Comment by klokan** [comment]
Thanks
