### ISSUE TITLE
Space under "[Archive catalogue]" and then faded/gray inactive "Categories:" title

### ISSUE THREAD

**Issue by klokan** [klokantech/bmarchives-tickets#9]
Put margin under "[Archive catalogue]" and then a faded/gray inactive "Categories:" title

Similar to:

![Screen Shot 2013-04-09 at 3 34 32 PM](https://f.cloud.github.com/assets/59284/356932/8f610b82-a11a-11e2-8b86-95f3e7fc964d.png)

**Comment by xurban42** [comment]
Done. Please check "Categories" title style - color, padding.
![screen shot 2013-11-27 at 15 27 34](https://f.cloud.github.com/assets/4047951/1631948/2c0e5262-5770-11e3-9826-9de72f9dbbab.png)

**Comment by klokan** [comment]
Only internal testing yet - deployment to the public server to be done by @o1da

**Comment by o1da** [comment]
Deployed
